version: '3.5'

# THESE OVERRIDES ARE FOR DEVELOPMENT! DON'T USE THIS IN PRODUCTION!
services:
  db:
    ports:
      # Allow us to directly access the database during development
      - "5432:5432"

  nginx:
    ports:
      # Will be available @ localhost:8000
      - "8000:80"

  django:
    # Automatically reload Gunicorn when a file changes
    command: gunicorn appname.wsgi -c gunicorn.cfg.py --reload
    environment:
      - DEBUG=true
